apiVersion: v1
kind: Service
metadata:
  name: {{.Values.api.service.name}}
spec:
  selector:
    app: {{.Values.api.deployment.name}}  # Seleciona os pods que correspondem a essa label
  ports:
    - name: http            # Nome da porta para referência interna (HTTP)
      protocol: TCP
      port: {{.Values.api.service.http.targetPort}}              # Porta externa do serviço Kubernetes
      targetPort: {{.Values.api.service.http.targetPort}}        # Porta no pod onde a sua aplicação está escutando
    - name: https           # Nome da porta para referência interna (HTTPS)
      protocol: TCP
      port: {{.Values.api.service.https.targetPort}}              # Porta externa do serviço Kubernetes
      targetPort: {{.Values.api.service.https.targetPort}}        # Porta no pod onde a sua aplicação está escutando
  type: LoadBalancer            # Tipo de serviço, pode ser LoadBalancer, NodePort, ou ClusterIP
