# templates/deployment1.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.deployment.name }}
spec:
  replicas: {{ .Values.api.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.api.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.api.deployment.name }}
    spec:
      containers:
      - name: {{ .Values.api.deployment.name }}
        image: "{{ .Values.api.deployment.image.repository }}:{{ if eq .Values.environment "production" }}latest{{ else }}dev{{ end }}"
        ports:
          - containerPort: 80   # Porta HTTP dentro do contêiner
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30  
          periodSeconds: 10        
          timeoutSeconds: 5        
          failureThreshold: 2     
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10  
          periodSeconds: 10        # Verifica a cada 10 segundos
          timeoutSeconds: 5        # Tempo limite de 5 segundos para a resposta
          failureThreshold: 2      # Número de falhas consecutivas para considerar o container como não pronto
        resources:
          requests:
            cpu: "512m"
            memory: "512Mi"
          limits:
            cpu: "2048m"
            memory: "2048Mi"
        env:
          - name: DBConnection
            valueFrom:
              configMapKeyRef:
                name: {{.Values.api.configmap.name}}  # Nome do ConfigMap que contém a configuração
                key: DBConnection  # Chave dentro do ConfigMap que contém a string de conexão
          - name: MERCADO_PAGO_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{.Values.api.secret.name}} 
                key: MERCADO_PAGO_TOKEN
          - name: MERCADO_PAGO_URL_WEBHOOK
            valueFrom:
              configMapKeyRef:
                name: {{.Values.api.configmap.name}} 
                key: MERCADO_PAGO_URL_WEBHOOK  
          - name: MERCADO_PAGO_USERID
            valueFrom:
              configMapKeyRef:
                name: {{.Values.api.configmap.name}} 
                key: MERCADO_PAGO_USERID  
          - name: MERCADO_PAGO_POSID
            valueFrom:
              configMapKeyRef:
                name: {{.Values.api.configmap.name}} 
                key: MERCADO_PAGO_POSID  