apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: controlepedido-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment  # Tipo de recurso que está sendo escalado
    name: controlepedido-api-pod  # Nome do deployment que você deseja escalar
  minReplicas: 1  # Número mínimo de réplicas
  maxReplicas: 10  # Número máximo de réplicas
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60  # Alvo de utilização de CPU (60%)
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 60  # Alvo de utilização de memória (60%)
