apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{.Values.api.hpa.name}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{.Values.api.deployment.name}}
  minReplicas: {{.Values.api.hpa.minReplicas}}  # Número mínimo de réplicas
  maxReplicas: {{.Values.api.hpa.maxReplicas}}  # Número máximo de réplicas
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{.Values.api.hpa.cpuAverageUtilization}}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{.Values.api.hpa.memoryAverageUtilization}}
