apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.database.deployment.volume.claimName}}
spec:
  accessModes:
    - ReadWriteOnce  # Modo de acesso ao volume
  resources:
    requests:
      storage: {{.Values.database.deployment.volume.storage}}  # Capacidade solicitada
  storageClassName: local-storage  # Classe de armazenamento (se estiver usando StorageClass)
